/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedPrayerRouteImport } from './routes/_protected/prayer'
import { Route as ProtectedExampleProtectedRouteRouteImport } from './routes/_protected/example-protected-route'
import { Route as ProtectedDonationsRouteImport } from './routes/_protected/donations'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedActivityRouteImport } from './routes/_protected/activity'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthVerificationPendingRouteImport } from './routes/_auth/verification-pending'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthResendVerificationRouteImport } from './routes/_auth/resend-verification'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthAccountLockedRouteImport } from './routes/_auth/account-locked'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as ProtectedTripsIndexRouteImport } from './routes/_protected/trips/index'
import { Route as ProtectedTripsNewRouteImport } from './routes/_protected/trips/new'
import { Route as ProtectedTripTripIdRouteImport } from './routes/_protected/trip.$tripId'
import { Route as PublicInvitePrayerTokenRouteImport } from './routes/_public/invite.prayer.$token'
import { Route as PublicInviteFollowerTokenRouteImport } from './routes/_public/invite.follower.$token'
import { Route as ProtectedTripsTripIdSettingsRouteImport } from './routes/_protected/trips.$tripId.settings'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPrayerRoute = ProtectedPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExampleProtectedRouteRoute =
  ProtectedExampleProtectedRouteRouteImport.update({
    id: '/example-protected-route',
    path: '/example-protected-route',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDonationsRoute = ProtectedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedActivityRoute = ProtectedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerificationPendingRoute = AuthVerificationPendingRouteImport.update({
  id: '/verification-pending',
  path: '/verification-pending',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResendVerificationRoute = AuthResendVerificationRouteImport.update({
  id: '/resend-verification',
  path: '/resend-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountLockedRoute = AuthAccountLockedRouteImport.update({
  id: '/account-locked',
  path: '/account-locked',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTripsIndexRoute = ProtectedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTripsNewRoute = ProtectedTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTripTripIdRoute = ProtectedTripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicInvitePrayerTokenRoute = PublicInvitePrayerTokenRouteImport.update({
  id: '/invite/prayer/$token',
  path: '/invite/prayer/$token',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInviteFollowerTokenRoute =
  PublicInviteFollowerTokenRouteImport.update({
    id: '/invite/follower/$token',
    path: '/invite/follower/$token',
    getParentRoute: () => PublicRoute,
  } as any)
const ProtectedTripsTripIdSettingsRoute =
  ProtectedTripsTripIdSettingsRouteImport.update({
    id: '/trips/$tripId/settings',
    path: '/trips/$tripId/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/hello': typeof ApiHelloRoute
  '/account-locked': typeof AuthAccountLockedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/resend-verification': typeof AuthResendVerificationRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verification-pending': typeof AuthVerificationPendingRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/activity': typeof ProtectedActivityRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/donations': typeof ProtectedDonationsRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/prayer': typeof ProtectedPrayerRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof PublicIndexRoute
  '/trip/$tripId': typeof ProtectedTripTripIdRoute
  '/trips/new': typeof ProtectedTripsNewRoute
  '/trips': typeof ProtectedTripsIndexRoute
  '/trips/$tripId/settings': typeof ProtectedTripsTripIdSettingsRoute
  '/invite/follower/$token': typeof PublicInviteFollowerTokenRoute
  '/invite/prayer/$token': typeof PublicInvitePrayerTokenRoute
}
export interface FileRoutesByTo {
  '/hello': typeof ApiHelloRoute
  '/account-locked': typeof AuthAccountLockedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/resend-verification': typeof AuthResendVerificationRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verification-pending': typeof AuthVerificationPendingRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/activity': typeof ProtectedActivityRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/donations': typeof ProtectedDonationsRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/prayer': typeof ProtectedPrayerRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof PublicIndexRoute
  '/trip/$tripId': typeof ProtectedTripTripIdRoute
  '/trips/new': typeof ProtectedTripsNewRoute
  '/trips': typeof ProtectedTripsIndexRoute
  '/trips/$tripId/settings': typeof ProtectedTripsTripIdSettingsRoute
  '/invite/follower/$token': typeof PublicInviteFollowerTokenRoute
  '/invite/prayer/$token': typeof PublicInvitePrayerTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_api/hello': typeof ApiHelloRoute
  '/_auth/account-locked': typeof AuthAccountLockedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/resend-verification': typeof AuthResendVerificationRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verification-pending': typeof AuthVerificationPendingRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/activity': typeof ProtectedActivityRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/donations': typeof ProtectedDonationsRoute
  '/_protected/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/_protected/prayer': typeof ProtectedPrayerRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/trip/$tripId': typeof ProtectedTripTripIdRoute
  '/_protected/trips/new': typeof ProtectedTripsNewRoute
  '/_protected/trips/': typeof ProtectedTripsIndexRoute
  '/_protected/trips/$tripId/settings': typeof ProtectedTripsTripIdSettingsRoute
  '/_public/invite/follower/$token': typeof PublicInviteFollowerTokenRoute
  '/_public/invite/prayer/$token': typeof PublicInvitePrayerTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/hello'
    | '/account-locked'
    | '/forgot-password'
    | '/resend-verification'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/verification-pending'
    | '/verify-email'
    | '/activity'
    | '/dashboard'
    | '/donations'
    | '/example-protected-route'
    | '/prayer'
    | '/settings'
    | '/'
    | '/trip/$tripId'
    | '/trips/new'
    | '/trips'
    | '/trips/$tripId/settings'
    | '/invite/follower/$token'
    | '/invite/prayer/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hello'
    | '/account-locked'
    | '/forgot-password'
    | '/resend-verification'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/verification-pending'
    | '/verify-email'
    | '/activity'
    | '/dashboard'
    | '/donations'
    | '/example-protected-route'
    | '/prayer'
    | '/settings'
    | '/'
    | '/trip/$tripId'
    | '/trips/new'
    | '/trips'
    | '/trips/$tripId/settings'
    | '/invite/follower/$token'
    | '/invite/prayer/$token'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_api/hello'
    | '/_auth/account-locked'
    | '/_auth/forgot-password'
    | '/_auth/resend-verification'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_auth/verification-pending'
    | '/_auth/verify-email'
    | '/_protected/activity'
    | '/_protected/dashboard'
    | '/_protected/donations'
    | '/_protected/example-protected-route'
    | '/_protected/prayer'
    | '/_protected/settings'
    | '/_public/'
    | '/_protected/trip/$tripId'
    | '/_protected/trips/new'
    | '/_protected/trips/'
    | '/_protected/trips/$tripId/settings'
    | '/_public/invite/follower/$token'
    | '/_public/invite/prayer/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/prayer': {
      id: '/_protected/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof ProtectedPrayerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/example-protected-route': {
      id: '/_protected/example-protected-route'
      path: '/example-protected-route'
      fullPath: '/example-protected-route'
      preLoaderRoute: typeof ProtectedExampleProtectedRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/donations': {
      id: '/_protected/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof ProtectedDonationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/activity': {
      id: '/_protected/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ProtectedActivityRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verification-pending': {
      id: '/_auth/verification-pending'
      path: '/verification-pending'
      fullPath: '/verification-pending'
      preLoaderRoute: typeof AuthVerificationPendingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resend-verification': {
      id: '/_auth/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof AuthResendVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-locked': {
      id: '/_auth/account-locked'
      path: '/account-locked'
      fullPath: '/account-locked'
      preLoaderRoute: typeof AuthAccountLockedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/trips/': {
      id: '/_protected/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof ProtectedTripsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/trips/new': {
      id: '/_protected/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof ProtectedTripsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/trip/$tripId': {
      id: '/_protected/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof ProtectedTripTripIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/invite/prayer/$token': {
      id: '/_public/invite/prayer/$token'
      path: '/invite/prayer/$token'
      fullPath: '/invite/prayer/$token'
      preLoaderRoute: typeof PublicInvitePrayerTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/invite/follower/$token': {
      id: '/_public/invite/follower/$token'
      path: '/invite/follower/$token'
      fullPath: '/invite/follower/$token'
      preLoaderRoute: typeof PublicInviteFollowerTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/trips/$tripId/settings': {
      id: '/_protected/trips/$tripId/settings'
      path: '/trips/$tripId/settings'
      fullPath: '/trips/$tripId/settings'
      preLoaderRoute: typeof ProtectedTripsTripIdSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountLockedRoute: typeof AuthAccountLockedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResendVerificationRoute: typeof AuthResendVerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerificationPendingRoute: typeof AuthVerificationPendingRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountLockedRoute: AuthAccountLockedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResendVerificationRoute: AuthResendVerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerificationPendingRoute: AuthVerificationPendingRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedActivityRoute: typeof ProtectedActivityRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDonationsRoute: typeof ProtectedDonationsRoute
  ProtectedExampleProtectedRouteRoute: typeof ProtectedExampleProtectedRouteRoute
  ProtectedPrayerRoute: typeof ProtectedPrayerRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTripTripIdRoute: typeof ProtectedTripTripIdRoute
  ProtectedTripsNewRoute: typeof ProtectedTripsNewRoute
  ProtectedTripsIndexRoute: typeof ProtectedTripsIndexRoute
  ProtectedTripsTripIdSettingsRoute: typeof ProtectedTripsTripIdSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedActivityRoute: ProtectedActivityRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDonationsRoute: ProtectedDonationsRoute,
  ProtectedExampleProtectedRouteRoute: ProtectedExampleProtectedRouteRoute,
  ProtectedPrayerRoute: ProtectedPrayerRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTripTripIdRoute: ProtectedTripTripIdRoute,
  ProtectedTripsNewRoute: ProtectedTripsNewRoute,
  ProtectedTripsIndexRoute: ProtectedTripsIndexRoute,
  ProtectedTripsTripIdSettingsRoute: ProtectedTripsTripIdSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInviteFollowerTokenRoute: typeof PublicInviteFollowerTokenRoute
  PublicInvitePrayerTokenRoute: typeof PublicInvitePrayerTokenRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicInviteFollowerTokenRoute: PublicInviteFollowerTokenRoute,
  PublicInvitePrayerTokenRoute: PublicInvitePrayerTokenRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
